export { default as authController } from './auth.controller'
export { default as userController } from './user.controller'
export { default as jobController } from './job.controller'
export { default as gameController } from './game.controller'
export { default as albumController } from './album.controller'
export { default as postController } from './post.controller'
export { default as adminController } from './admin.controller'
export { default as uploadController } from './upload.controller'
